apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deploy
  labels:
    app: webapp-deploy
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: webapp-deploy
  template:
    metadata:
      labels:
        app: webapp-deploy
    spec:
      containers:
        - name: {{ .Release.Name}}-web
          image: {{ .Values.image.repository }}
          ports:
            - containerPort: {{ .Values.image.containerPorts }}
