name: Different contexts
on: workflow_dispatch

jobs:
  if-Windows-else:
    runs-on: macos-latest
    steps:
      - name: condition 1
        if: runner.os == 'Windows'
        run: echo "The operating system on the runner is $env:RUNNER_OS."
      - name: condition 2
        if: runner.os != 'Windows'
        run: echo "The operating system on the runner is not Windows, it's $RUNNER_OS."
      - name: github context examples
        run: |
          echo "Git repository id= ${{ github.repository_id }}"
          echo "Git Url = ${{ github.repositoryUrl }}"
          echo "Git Run id = ${{ github.run_id }}"
          echo "Git workspace = ${{ github.workspace }}"
      - name: Create annotation for build error
        run: echo "::error file=app.js,line=1::Missing semicolon"
      - name: Group of log lines
        run: |
            echo "::group::My title"
            echo "Inside group"
            echo "::endgroup::"        
